version: '2.3'

services:
  citadel-bionic-dev:
    image: tiger0421/docker-lio-sam:latest
    container_name: lio-sam
    runtime: nvidia
    network_mode: "host"
    privileged: true
    group_add:
      - video
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - MESA_GL_VERSION_OVERRIDE=4.2
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    working_dir: /root
    tty: true
    command: gazebo

volumes:
  ign:
